#!/usr/bin/env python
"""
Seed 110+ grammar questions into the database.
Run from the backend/ folder:
    venv\Scripts\python seed_grammar.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app.api.db_setup import SessionLocal
from app.api.models import GrammarQuestion

QUESTIONS = [
    # ── Present tense ──────────────────────────────────────────────────────
    {
        "question": "Jag ___ i Göteborg sedan fem år.",
        "correct_answer": "bor",
        "choices": ["bor", "bodde", "bott", "bo"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Han ___ till jobbet med cykel varje dag.",
        "correct_answer": "åker",
        "choices": ["åker", "åkte", "åkt", "åka"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Vi ___ svenska på universitetet.",
        "correct_answer": "studerar",
        "choices": ["studerar", "studerade", "studerat", "studera"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Hon ___ alltid tidigt på morgonen.",
        "correct_answer": "vaknar",
        "choices": ["vaknar", "vaknade", "vaknat", "vakna"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Barnen ___ i trädgården just nu.",
        "correct_answer": "leker",
        "choices": ["leker", "lekte", "lekt", "leka"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Jag ___ ett brev till min mamma.",
        "correct_answer": "skriver",
        "choices": ["skriver", "skrev", "skrivit", "skriva"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Du ___ bra på engelska.",
        "correct_answer": "pratar",
        "choices": ["pratar", "pratade", "pratat", "prata"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Vi ___ mat till middag varje kväll.",
        "correct_answer": "lagar",
        "choices": ["lagar", "lagade", "lagat", "laga"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Hon ___ sig i spegeln varje morgon.",
        "correct_answer": "ser",
        "choices": ["ser", "såg", "sett", "se"],
        "category": "present",
        "level": None,
    },
    {
        "question": "De ___ mycket om helgerna.",
        "correct_answer": "sover",
        "choices": ["sover", "sov", "sovit", "sova"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Han ___ mycket böcker på fritiden.",
        "correct_answer": "läser",
        "choices": ["läser", "läste", "läst", "läsa"],
        "category": "present",
        "level": None,
    },
    {
        "question": "Jag ___ kaffe varje morgon.",
        "correct_answer": "dricker",
        "choices": ["dricker", "drack", "druckit", "dricka"],
        "category": "present",
        "level": None,
    },

    # ── Past tense ─────────────────────────────────────────────────────────
    {
        "question": "Igår ___ jag till biblioteket.",
        "correct_answer": "gick",
        "choices": ["gick", "går", "gå", "har gått"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Hon ___ en film förra kvällen.",
        "correct_answer": "såg",
        "choices": ["ser", "såg", "sett", "se"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Vi ___ lunch på restaurangen igår.",
        "correct_answer": "åt",
        "choices": ["äter", "åt", "ätit", "äta"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Han ___ sent hem igår kväll.",
        "correct_answer": "kom",
        "choices": ["kommer", "kom", "kommit", "komma"],
        "category": "past",
        "level": None,
    },
    {
        "question": "De ___ i Paris förra sommaren.",
        "correct_answer": "bodde",
        "choices": ["bor", "bodde", "bott", "bo"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Jag ___ brevet till chefen i morse.",
        "correct_answer": "skickade",
        "choices": ["skickar", "skickade", "skickat", "skicka"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Hon ___ ett nytt jobb förra månaden.",
        "correct_answer": "fick",
        "choices": ["får", "fick", "fått", "få"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Barnet ___ hela natten.",
        "correct_answer": "sov",
        "choices": ["sover", "sov", "sovit", "sova"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Han ___ bilen utanför huset igår.",
        "correct_answer": "parkerade",
        "choices": ["parkerar", "parkerade", "parkerat", "parkera"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Vi ___ hela natten och var trötta nästa dag.",
        "correct_answer": "dansade",
        "choices": ["dansar", "dansade", "dansat", "dansa"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Hon ___ sin plånbok i affären.",
        "correct_answer": "glömde",
        "choices": ["glömmer", "glömde", "glömt", "glömma"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Jag ___ honom på tåget förra veckan.",
        "correct_answer": "träffade",
        "choices": ["träffar", "träffade", "träffat", "träffa"],
        "category": "past",
        "level": None,
    },
    {
        "question": "De ___ fotboll i tre timmar igår.",
        "correct_answer": "spelade",
        "choices": ["spelar", "spelade", "spelat", "spela"],
        "category": "past",
        "level": None,
    },
    {
        "question": "Han ___ upp klockan sex imorse.",
        "correct_answer": "steg",
        "choices": ["stiger", "steg", "stigit", "stiga"],
        "category": "past",
        "level": None,
    },

    # ── Perfect tense ──────────────────────────────────────────────────────
    {
        "question": "Jag ___ aldrig besökt Norge.",
        "correct_answer": "har",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "Hon ___ redan ätit frukost.",
        "correct_answer": "har",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "Vi ___ studerat svenska i två år.",
        "correct_answer": "har",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "Han ___ precis kommit hem när telefonen ringde.",
        "correct_answer": "hade",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "De ___ inte sett den filmen ännu.",
        "correct_answer": "har",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "Jag ___ bott i Stockholm i fem år.",
        "correct_answer": "har",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },
    {
        "question": "Hon ___ jobbat hela dagen när chefen ringde.",
        "correct_answer": "hade",
        "choices": ["har", "hade", "är", "var"],
        "category": "perfect",
        "level": None,
    },

    # ── Modal verbs ────────────────────────────────────────────────────────
    {
        "question": "Du ___ inte röka här inne.",
        "correct_answer": "får",
        "choices": ["får", "kan", "ska", "vill"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Jag ___ inte simma. Kan du lära mig?",
        "correct_answer": "kan",
        "choices": ["kan", "får", "ska", "bör"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Hon ___ bli läkare när hon blir stor.",
        "correct_answer": "vill",
        "choices": ["vill", "kan", "ska", "bör"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Vi ___ träffas imorgon klockan tre.",
        "correct_answer": "ska",
        "choices": ["ska", "kan", "får", "vill"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Du ___ träna mer om du vill bli bättre.",
        "correct_answer": "bör",
        "choices": ["bör", "ska", "kan", "vill"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Barnen ___ leka i parken ensamma.",
        "correct_answer": "får inte",
        "choices": ["får inte", "kan inte", "ska inte", "vill inte"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Jag ___ hjälpa dig om du behöver.",
        "correct_answer": "kan",
        "choices": ["kan", "vill", "ska", "bör"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Hon ___ studera mer inför provet.",
        "correct_answer": "måste",
        "choices": ["måste", "kan", "vill", "ska"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "De ___ ta tåget eller bussen till centrum.",
        "correct_answer": "kan",
        "choices": ["kan", "måste", "bör", "vill"],
        "category": "modal",
        "level": None,
    },
    {
        "question": "Jag ___ gärna ha lite mer kaffe.",
        "correct_answer": "vill",
        "choices": ["vill", "ska", "måste", "bör"],
        "category": "modal",
        "level": None,
    },

    # ── Articles en/ett ────────────────────────────────────────────────────
    {
        "question": "Det är ___ stor hund i trädgården.",
        "correct_answer": "en",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Det är ___ litet barn som leker.",
        "correct_answer": "ett",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Jag har ___ ny cykel.",
        "correct_answer": "en",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Hon läser ___ intressant bok.",
        "correct_answer": "en",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Vi bor i ___ stort hus.",
        "correct_answer": "ett",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Det finns ___ bra restaurang på hörnet.",
        "correct_answer": "en",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Jag behöver köpa ___ nytt paraply.",
        "correct_answer": "ett",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Han har ___ konstig dröm varje natt.",
        "correct_answer": "en",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Det är ___ fantastiskt museum i staden.",
        "correct_answer": "ett",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },
    {
        "question": "Vi fick ___ brev från Sverige.",
        "correct_answer": "ett",
        "choices": ["en", "ett", "den", "det"],
        "category": "articles",
        "level": None,
    },

    # ── Adjective agreement ────────────────────────────────────────────────
    {
        "question": "Det är en ___ bil. (röd)",
        "correct_answer": "röd",
        "choices": ["röd", "rött", "röda", "röde"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är ett ___ hus. (röd)",
        "correct_answer": "rött",
        "choices": ["röd", "rött", "röda", "röde"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "De är ___ bilar. (röd)",
        "correct_answer": "röda",
        "choices": ["röd", "rött", "röda", "röde"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är en ___ katt. (stor)",
        "correct_answer": "stor",
        "choices": ["stor", "stort", "stora", "store"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är ett ___ barn. (glad)",
        "correct_answer": "glatt",
        "choices": ["glad", "glatt", "glada", "glade"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Hon har ___ ögon. (blå)",
        "correct_answer": "blå",
        "choices": ["blå", "blått", "blåa", "blåe"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är ett ___ problem. (stor)",
        "correct_answer": "stort",
        "choices": ["stor", "stort", "stora", "store"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Vi bor i ett ___ hus. (gammal)",
        "correct_answer": "gammalt",
        "choices": ["gammal", "gammalt", "gamla", "gamle"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är en ___ dag. (vacker)",
        "correct_answer": "vacker",
        "choices": ["vacker", "vackert", "vackra", "vackre"],
        "category": "adjective",
        "level": None,
    },
    {
        "question": "Det är ett ___ väder. (vacker)",
        "correct_answer": "vackert",
        "choices": ["vacker", "vackert", "vackra", "vackre"],
        "category": "adjective",
        "level": None,
    },

    # ── Comparative & superlative ──────────────────────────────────────────
    {
        "question": "Stockholm är ___ än Malmö. (stor)",
        "correct_answer": "större",
        "choices": ["större", "störst", "stor", "storare"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Det är den ___ staden i Sverige. (stor)",
        "correct_answer": "största",
        "choices": ["störst", "största", "större", "storaste"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Idag är det ___ än igår. (kallt)",
        "correct_answer": "kallare",
        "choices": ["kallare", "kallast", "kallt", "mer kall"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Det är det ___ alternativet. (bra)",
        "correct_answer": "bästa",
        "choices": ["bättre", "bäst", "bästa", "godaste"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Hon sjunger ___ av alla. (bra)",
        "correct_answer": "bäst",
        "choices": ["bättre", "bäst", "bästa", "godast"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Den här vägen är ___ än den andra. (lång)",
        "correct_answer": "längre",
        "choices": ["längre", "längst", "lång", "mer lång"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Det är den ___ filmen jag sett. (dålig)",
        "correct_answer": "sämsta",
        "choices": ["sämre", "sämst", "sämsta", "dåligaste"],
        "category": "comparative",
        "level": None,
    },
    {
        "question": "Han springer ___ än sin bror. (snabb)",
        "correct_answer": "snabbare",
        "choices": ["snabbare", "snabbast", "snabb", "mer snabb"],
        "category": "comparative",
        "level": None,
    },

    # ── Prepositions ───────────────────────────────────────────────────────
    {
        "question": "Boken ligger ___ bordet.",
        "correct_answer": "på",
        "choices": ["på", "i", "under", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Jag bor ___ en liten stad.",
        "correct_answer": "i",
        "choices": ["i", "på", "till", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Hon åker ___ skolan varje morgon.",
        "correct_answer": "till",
        "choices": ["till", "på", "i", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Katten sover ___ soffan.",
        "correct_answer": "på",
        "choices": ["på", "under", "i", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Vi ses ___ måndag.",
        "correct_answer": "på",
        "choices": ["på", "i", "till", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Hon kom ___ Danmark förra veckan.",
        "correct_answer": "från",
        "choices": ["från", "av", "till", "med"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Jag läser ___ kvällen.",
        "correct_answer": "på",
        "choices": ["på", "i", "om", "av"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Nyckeln ligger ___ väskan.",
        "correct_answer": "i",
        "choices": ["i", "på", "av", "under"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "De pratar ___ svenska.",
        "correct_answer": "på",
        "choices": ["på", "i", "av", "med"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Hon skriver ___ penna, inte dator.",
        "correct_answer": "med",
        "choices": ["med", "på", "av", "i"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Jag är intresserad ___ historia.",
        "correct_answer": "av",
        "choices": ["av", "på", "i", "med"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Han är rädd ___ hundar.",
        "correct_answer": "för",
        "choices": ["för", "av", "på", "med"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Tåget avgår ___ klockan tio.",
        "correct_answer": "klockan",
        "choices": ["klockan", "vid", "i", "på"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Butiken stänger ___ sex.",
        "correct_answer": "vid",
        "choices": ["vid", "på", "till", "om"],
        "category": "preposition",
        "level": None,
    },
    {
        "question": "Jag jobbar ___ måndag till fredag.",
        "correct_answer": "från",
        "choices": ["från", "av", "på", "mellan"],
        "category": "preposition",
        "level": None,
    },

    # ── Pronouns ───────────────────────────────────────────────────────────
    {
        "question": "___ heter Anna och är lärare.",
        "correct_answer": "Hon",
        "choices": ["Hon", "Honom", "Henne", "Hans"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Jag träffade ___ på tåget igår.",
        "correct_answer": "henne",
        "choices": ["hon", "henne", "hennes", "sig"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Det är ___ bok. (belonging to Anna)",
        "correct_answer": "hennes",
        "choices": ["hon", "henne", "hennes", "sin"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Han tog ___ jacka och gick.",
        "correct_answer": "sin",
        "choices": ["hans", "sin", "sig", "honom"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Vi bjöd ___ på middag igår.",
        "correct_answer": "dem",
        "choices": ["de", "dem", "deras", "sig"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "___ är en bra idé.",
        "correct_answer": "Det",
        "choices": ["Den", "Det", "De", "Dem"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Vem är ___? Det är jag!",
        "correct_answer": "det",
        "choices": ["den", "det", "de", "dem"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Han tvättar ___ varje morgon.",
        "correct_answer": "sig",
        "choices": ["honom", "hans", "sig", "sin"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Vi tog ___ med oss på resan.",
        "correct_answer": "barnen",
        "choices": ["dem", "de", "barnen", "sig"],
        "category": "pronoun",
        "level": None,
    },
    {
        "question": "Boken tillhör ___. (to me)",
        "correct_answer": "mig",
        "choices": ["jag", "mig", "min", "mitt"],
        "category": "pronoun",
        "level": None,
    },

    # ── Negation & word order ──────────────────────────────────────────────
    {
        "question": "Jag förstår ___ vad du menar.",
        "correct_answer": "inte",
        "choices": ["inte", "ej", "icke", "aldrig"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Hon talar ___ franska.",
        "correct_answer": "inte",
        "choices": ["inte", "ej", "icke", "aldrig"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Det finns ___ mat kvar.",
        "correct_answer": "ingen",
        "choices": ["ingen", "inget", "inga", "inte"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Det finns ___ barn i parken idag.",
        "correct_answer": "inga",
        "choices": ["ingen", "inget", "inga", "inte"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Det finns ___ problem med datorn.",
        "correct_answer": "inget",
        "choices": ["ingen", "inget", "inga", "inte"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Jag har ___ träffat honom förut.",
        "correct_answer": "aldrig",
        "choices": ["aldrig", "inte", "ej", "icke"],
        "category": "negation",
        "level": None,
    },
    {
        "question": "Imorgon ___ jag till Paris.",
        "correct_answer": "åker",
        "choices": ["åker", "jag åker", "åka", "ska åka"],
        "category": "word_order",
        "level": None,
    },
    {
        "question": "Nu ___ vi börja.",
        "correct_answer": "måste",
        "choices": ["måste", "vi måste", "måste vi", "ska"],
        "category": "word_order",
        "level": None,
    },
    {
        "question": "Varje dag ___ han på jobbet klockan åtta.",
        "correct_answer": "är",
        "choices": ["är", "han är", "vara", "var"],
        "category": "word_order",
        "level": None,
    },
    {
        "question": "Jag vet att hon ___ trött.",
        "correct_answer": "är",
        "choices": ["är", "inte är", "är inte", "var"],
        "category": "word_order",
        "level": None,
    },

    # ── Question words ─────────────────────────────────────────────────────
    {
        "question": "___ heter du?",
        "correct_answer": "Vad",
        "choices": ["Vad", "Var", "Vem", "Hur"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ bor du?",
        "correct_answer": "Var",
        "choices": ["Vad", "Var", "Vem", "Hur"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ gammal är du?",
        "correct_answer": "Hur",
        "choices": ["Hur", "Vad", "Var", "Vem"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ är det? (asking about a person)",
        "correct_answer": "Vem",
        "choices": ["Vem", "Vad", "Var", "Hur"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ kommer du? (asking about origin)",
        "correct_answer": "Varifrån",
        "choices": ["Varifrån", "Var", "Vart", "Hur"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ åker du? (asking about destination)",
        "correct_answer": "Vart",
        "choices": ["Vart", "Var", "Varifrån", "Hur"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ börjar filmen?",
        "correct_answer": "När",
        "choices": ["När", "Var", "Hur", "Vad"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ kostar det?",
        "correct_answer": "Vad",
        "choices": ["Vad", "Hur", "Var", "Vem"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ dags är det?",
        "correct_answer": "Vad",
        "choices": ["Vad", "Hur", "När", "Var"],
        "category": "question_words",
        "level": None,
    },
    {
        "question": "___ länge har du bott här?",
        "correct_answer": "Hur",
        "choices": ["Hur", "Vad", "När", "Var"],
        "category": "question_words",
        "level": None,
    },

    # ── Conjunctions ───────────────────────────────────────────────────────
    {
        "question": "Jag stannar hemma ___ det regnar.",
        "correct_answer": "om",
        "choices": ["om", "att", "när", "för"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Hon sa ___ hon var trött.",
        "correct_answer": "att",
        "choices": ["att", "om", "när", "för"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Jag gillar kaffe ___ te.",
        "correct_answer": "och",
        "choices": ["och", "eller", "men", "utan"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Hon vill studera, ___ hon har inte tid.",
        "correct_answer": "men",
        "choices": ["men", "och", "eller", "att"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "___ jag åt middag, tittade jag på TV.",
        "correct_answer": "Medan",
        "choices": ["Medan", "Om", "Eftersom", "Att"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Jag lärde mig svenska ___ jag bodde i Stockholm.",
        "correct_answer": "när",
        "choices": ["när", "om", "att", "för"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Han köpte en ny bil ___ den gamla gick sönder.",
        "correct_answer": "eftersom",
        "choices": ["eftersom", "när", "om", "att"],
        "category": "conjunction",
        "level": None,
    },
    {
        "question": "Vill du ha kaffe ___ te?",
        "correct_answer": "eller",
        "choices": ["eller", "och", "men", "utan"],
        "category": "conjunction",
        "level": None,
    },
]


def seed():
    db = SessionLocal()
    added = 0
    skipped = 0
    for q in QUESTIONS:
        exists = db.query(GrammarQuestion).filter_by(question=q["question"]).first()
        if exists:
            skipped += 1
            continue
        db.add(GrammarQuestion(
            question=q["question"],
            correct_answer=q["correct_answer"],
            choices=q["choices"],
            category=q["category"],
            level=q["level"],
        ))
        added += 1
    db.commit()
    db.close()
    print(f"Done! Added {added} questions, skipped {skipped} duplicates.")
    print(f"Total questions in list: {len(QUESTIONS)}")


if __name__ == "__main__":
    seed()
