"""add search history table

Revision ID: d4eb7ac703e6
Revises: f578ad41cbb6
Create Date: 2026-02-22 06:48:12.450402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eb7ac703e6'
down_revision: Union[str, Sequence[str], None] = 'f578ad41cbb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('word', sa.String(length=120), nullable=False))
    op.drop_constraint(op.f('search_history_user_id_fkey'), 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'])
    op.drop_column('search_history', 'result_article')
    op.drop_column('search_history', 'confidence')
    op.drop_column('search_history', 'normalized')
    op.drop_column('search_history', 'query')
    op.drop_column('search_history', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('search_history', sa.Column('query', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('search_history', sa.Column('normalized', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('search_history', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('search_history', sa.Column('result_article', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key(op.f('search_history_user_id_fkey'), 'search_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('search_history', 'word')
    # ### end Alembic commands ###
